# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://pistocop.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /pistoBot-website

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Simone Guardati"
title: "pistoBot"
description: "Create an AI that (tries) to chat like you."
keywords: "pistobot, whatsapp, telegram, ai, gpt2, rnn, generative"
favicon: "/img/robotic.png"


################
# Header layout #
################

black-favicon: "/img/robotic.png"

background-img: "../img/copywriter.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: " pistoBot say: dio caro mi gasi"
  - text: " pistoBot say: domani sborniaccia?"
  - text: " pistoBot say: Che spettacolo!"
  - text: " pistoBot say: per簷 sono ancora un p簷 scemo"
  - text: " pistoBot say: Sei proprio il top del top"

#me-img: "/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/pistocop.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

#icon-36p: "/img/web-app/icon-36p.png"
#icon-48p: "/img/web-app/icon-48p.png"
#icon-72p: "/img/web-app/icon-72p.png"
#icon-96p: "/img/web-app/icon-96p.png"
#icon-144p: "/img/web-app/icon-144p.png"
#icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

#post-preview-words: 96
#
#paginate: 5
#
#email-share: True
#fb-share: True
#twitter-share: True
#linkedin-share: True
#reddit-share: True
#google-plus-share: True
#tumblr-share: True
#pinterest-share: True
#pocket-share: True
#vkontakte-share: True
#
#disqus-shortname: "personal-jekyll-theme"
#
#syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/virus.svg"
    date: "11 March 2020"
    description: "The coronavirus forces me to stay locked in my room."
  - image: "/img/timeline/message.svg"
    date: "April 2020"
    description: "Develop the whatsapp and telegram parser.<br>[Github](https://github.com/pistocop/messaging-chat-parser)"
  - image: "/img/timeline/python.svg"
    date: "April 2020"
    description: "Develop a RNN generative model.<br>[Github](https://github.com/pistocop/pistoBot/tree/master/pistoBot)"
  - image: "/img/timeline/connection.svg"
    date: "May 2020"
    description: "Develop a gpt2 pre-trained generative model based on [gpt-2-simple](https://github.com/minimaxir/gpt-2-simple).<br>[Github](https://github.com/pistocop/pistoBot/tree/master/pistoBot)"
  - image: "/img/timeline/search.svg"
    date: "May 2020 - Now"
    description: "Create my first website (this), based on [personal-jekyll-theme](https://github.com/le4ker/personal-jekyll-theme)"
  - image: "/img/timeline/knowledge.svg"
    date: "June 2020"
    description: "Develop a gpt2 generative model based on [aitextgen](https://github.com/minimaxir/aitextgen).<br>[Github](https://github.com/pistocop/pistoBot/tree/master/pistoBot)"

# First image of the Timeline

timeline-img: "/img/timeline/magical.svg"

###########
# Contact #
###########

#email: "simone.guardati42+pistoBot@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
#author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
#  - title: "facebook"
#    url: "https://facebook.com/"
#  - title: "twitter"
#    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/pistocop/pistoBot"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
#  - title: "rss"
#    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/attention_white.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Description: 'about'
  Timeline: 'timeline'
  Notes: 'notes'


# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

#paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
